
name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web for Github Pages
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: |
          cd example
          flutter config --enable-web
          flutter pub get
      - run: |
         cd example
         flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
      - run: |
          cd example/build/web
          git init
          git config --global user.email git@julianassmann.de
          git config --global user.name "Julian Aßmann"
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/JulianAssmann/flutter_gauges.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Update web"
          git push origin gh-pages -f
